Repository stolostron/multicloud-operators-deployable, pull requests merged in 2019-11, with the labels that each got.

#18 deploy target template packageOverrides to the subscription template …
  pkg/controller/deployable/rollingupdate.go
  pkg/utils/override.go
Labels: approved, lgtm, size/M

#19 move to operatorsdk 0.12.0
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/apis/app/v1alpha1/register.go
  pkg/controller/deployable/deployable_controller.go
  pkg/controller/deployable/deployable_controller_test.go
  pkg/controller/deployable/propagation.go
  pkg/utils/util_test.go
  tools.go
Labels: approved, lgtm, size/XL

#20 update yaml package
  go.mod
  go.sum
  pkg/utils/kubernetes.go
Labels: approved, lgtm, size/XS

#21 managed cluster annotation is not used in deployable
  pkg/controller/deployable/deployable_controller.go
Labels: approved, lgtm, size/S

#22 deployable hub controller PropagatedStatus update issues
  pkg/controller/deployable/deployable_controller.go
  pkg/controller/deployable/propagation.go
  pkg/controller/deployable/rollingupdate.go
  pkg/controller/deployable/template.go
  pkg/utils/deployable.go
Labels: approved, lgtm, size/L
