Repository stolostron/multicloud-operators-deployable, pull requests merged in 2019-10, with the labels that each got.

#1 Add myself as owner
  OWNERS
Labels: approved, lgtm, size/XS

#2 initial check with crd types only
  .gitignore
  .travis.yml
  CONTRIBUTING.md
  Makefile
  OWNERS
  RELEASE.md
  build/Dockerfile
  build/bin/entrypoint
  build/bin/user_setup
  cmd/manager/main.go
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/.hadolint.yml
  common/config/.yamllint.yml
  common/config/mdl.rb
  common/config/sass-lint.yml
  common/config/tslint.json
  common/scripts/config_docker.sh
  common/scripts/gobuild.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/lint_go.sh
  deploy/crds/app_v1alpha1_deployable_cr.yaml
  deploy/crds/app_v1alpha1_deployable_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  docs/development.md
  go.mod
  go.sum
  hack/boilerplate.go.txt
  hack/test/crds/cluster-registry-crd.yaml
  pkg/apis/addtoscheme_app_v1alpha1.go
  pkg/apis/apis.go
  pkg/apis/app/group.go
  pkg/apis/app/v1alpha1/deployable_types.go
  pkg/apis/app/v1alpha1/doc.go
  pkg/apis/app/v1alpha1/register.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/controller/add_deployable.go
  pkg/controller/controller.go
  pkg/controller/deployable/deployable_controller.go
  tools.go
  version/version.go
Labels: approved, lgtm, size/XXL

#4 use function provided by placmentrule for placement
  common/config/.golangci.yml
  go.mod
  go.sum
  hack/test/crds/app_v1alpha1_placementrule_crd.yaml
  pkg/apis/apis.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/deployable/deployable_controller.go
  pkg/controller/deployable/deployable_controller_test.go
  pkg/controller/deployable/placement.go
  pkg/controller/deployable/propagation.go
  pkg/utils/deployable.go
  pkg/utils/kubernetes.go
Labels: approved, lgtm, size/XL

#5 fix 1.20 golangci-lint issues
  cmd/exec/manager.go
  cmd/exec/options.go
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/apis/app/v1alpha1/deployable_types_test.go
  pkg/apis/app/v1alpha1/v1alpha1_suite_test.go
  pkg/controller/controller.go
  pkg/controller/deployable/dependencies.go
  pkg/controller/deployable/deployable_controller.go
  pkg/controller/deployable/deployable_controller_suite_test.go
  pkg/controller/deployable/deployable_controller_test.go
  pkg/controller/deployable/placement.go
  pkg/controller/deployable/propagation.go
  pkg/controller/deployable/rollingupdate.go
  pkg/controller/deployable/template.go
  pkg/utils/deployable.go
  pkg/utils/eventlog.go
  pkg/utils/kubernetes.go
  pkg/utils/override.go
Labels: approved, lgtm, size/XL

#6 update Makefile and Dockerfile to have a full make, except push
  Dockerfile
  Makefile
  cmd/manager/exec/manager.go
  cmd/manager/exec/options.go
  cmd/manager/main.go
Labels: approved, lgtm, size/M

#7 move to prow
  .travis.yml
  Makefile
  README.md
  common/Makefile.common.mk
  common/config/.golangci.yml
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#8 remove test dependency from build task
  Makefile
Labels: approved, lgtm, size/XS

#11 add badge and update sdk version to 0.10.0 for compatibility
  Makefile
  README.md
  common/scripts/codecov.sh
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#12 several fixes in rolling update, validate deployable and unit test enhancements
  Makefile
  examples/configmap-hub-deployable.yaml
  examples/rollingupdate/rollingupdate-configmap.yaml
  examples/rollingupdate/rollingupdate-version-configmap.yaml
  pkg/controller/deployable/deployable_controller.go
  pkg/controller/deployable/deployable_controller_test.go
  pkg/controller/deployable/propagation.go
  pkg/controller/deployable/rollingupdate.go
Labels: approved, lgtm, size/L

#15 add verification
  OWNERS
  deploy/operator.yaml
  docs/development.md
Labels: approved, lgtm, size/S

#14 Test
  pkg/controller/deployable/deployable_controller.go
  pkg/controller/deployable/deployable_controller_suite_test.go
  pkg/controller/deployable/deployable_controller_test.go
  pkg/controller/deployable/rollingupdate.go
  pkg/controller/deployable/template.go
  pkg/utils/deployable.go
Labels: approved, lgtm, size/XL

#16 add missing json for dependencies
  deploy/crds/app_v1alpha1_deployable_crd.yaml
  hack/test/app_v1alpha1_placementrule_crd.yaml
  hack/test/cluster-registry-crd.yaml
  pkg/apis/app/v1alpha1/deployable_types.go
  pkg/controller/deployable/deployable_controller_suite_test.go
Labels: approved, lgtm, size/M

#17 add util and separate signal
  cmd/manager/exec/manager.go
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/controller/deployable/propagation.go
  pkg/controller/deployable/template.go
  pkg/utils/eventlog.go
  pkg/utils/kubernetes.go
  pkg/utils/util_suite_test.go
  pkg/utils/util_test.go
Labels: approved, lgtm, size/L
