Repository stolostron/multicloud-operators-deployable, pull requests merged in 2021-04, with the labels that each got.

#73 CVE-2020-14040 fix - golang.org/x/text
  go.mod
  go.sum
Labels: approved, lgtm

#74 show unit test coverage percentage
  Makefile
Labels: approved

#75 update prow docker base image
  build/Dockerfile.prow
Labels: approved, dco-signoff: yes, lgtm

#76 Add unit tests for utils package
  pkg/utils/deployable_test.go
  pkg/utils/util_suite_test.go
  pkg/utils/util_test.go
Labels: approved, dco-signoff: yes, lgtm

#77 add release main branch
  RELEASE_MAIN_BRANCH
Labels: approved, dco-signoff: yes, lgtm

#78 Generate new image to fix CVE
  README.md
Labels: approved, dco-signoff: yes, lgtm

#80 go 16
  build/Dockerfile.prow
  go.mod
Labels: approved, dco-signoff: yes, lgtm

#83 remove codecov
  Makefile
  common/scripts/codecov.sh
Labels: approved, dco-signoff: yes, lgtm
